# Generated by Django 2.0.6 on 2018-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
