# Generated by Django 2.0.6 on 2018-06-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
