# Generated by Django 2.0.6 on 2018-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='memo_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='posting_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
